language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - bookdown

script:
  - mkdir docs/
  - cp -r _book/ docs/

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $tokens                   # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master
