language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - bookdown

before_script:
  - chmod +x ./_build.sh


script:
  - ./_build.sh
  - mkdir docs/
  - cp -r _book/ docs/

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master
