language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - bookdown

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: _book                        # Deploy the _books folder
  on:
    branch: gh-pages
