--- 
title: "Open Science MOOC Book"
author: "Samuel Guay on behalf of the Open Science MOOC Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: opensciencemooc/book
description: "This is an example of using the bookdown package to write the Open Science MOOC Book that will link all modules and supplemental material."
---

# Preface {-}

<center> **OPEN SCIENCE MOOC** </center>

***We want to help make open the default setting for all global research.*** *We want to develop a peer-to-peer, value-based community that works towards better science for society. Our ultimate goal is to help make ‘open’ the default setting for all global research, through creating and connecting a welcoming and supporting community, based around good tools, teachers, and role models, fundamentally built upon a solid values-based foundation of freedom and equitable access to research.*


## Warning - Tentative book {-}
As of now, this book is purely done out of free time here and there and serve only as a proof of concept to provide a portable/downloadable format for the Open Science MOOC content available on Eliademy. This is an example of using the bookdown package to write the Open Science MOOC Book that will link all modules and supplemental material.

## Rationale {-}
Research is getting a global makeover, in part thanks to the power of the internet and the tools it provides for us, and in part due to a growing call for accountability (e.g., reproducibility and data provenance) in research. Global policies are emerging at different levels that include some aspect of Open Research, Open Scholarship, or Open Science, and inclusive of all research disciplines. But our universities are often letting us down, and they are not teaching us the knowledge, tools and skills we need to do research effectively in the 21st century.

Open Science is about increased rigour, accountability, reproducibility for research. It is based on the principles of inclusion, fairness, equity, and sharing. Open Science can be viewed as research simply done properly, and it extends across the Life and Physical Sciences, Engineering, and Mathematics, to Social Science and Humanities.

This MOOC is designed to help equip students and researchers with the skills they need to excel in a modern research environment. It brings together the efforts and resources of hundreds of researchers and practitioners who have all dedicated their time and experience to create a community platform to help propel research forward.

The content of this MOOC will be distilled into 10 core modules. Each module will comprise a complete range of resources including videos, research articles, dummy datasets and code, as well as tasks to complete as individuals or groups.

The MOOC will be hosted through an open source provider. We expect that in the future different systems of certification will be developed, including completion badges. We also intend to build a forum for the open discussion of the MOOC and any relevant topics.

*Disclaimer:* We, the contributors, are fully aware that there is no magic one size fits all solution when it comes to implementing Open Science philosophies and best practices, especially when covering all research disciplines. However, we also believe that we should not limit ourselves from the onset, just because pragmatic solutions may not exist today for certain disciplines. We aim to set a highly inclusive standard, fully accepting the risk that for some disciplines this strategy may not be fully appropriate. Through that failure, we hope that you, the course users, will join us as course contributors and help us co-create bespoke solutions to your discipline based on principles of transparency, provenance, reproducibility and reuse of knowledge.

